# Generated by Django 6.0.1 on 2026-02-01 18:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('company_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last desktop app sync', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_employees', models.IntegerField(default=5, help_text='Max employees allowed')),
                ('max_storage_gb', models.IntegerField(default=10, help_text='Max storage in GB')),
                ('screenshot_retention_days', models.IntegerField(default=30)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['max_employees'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('OWNER', 'Software Owner'), ('ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10)),
                ('designation', models.CharField(blank=True, help_text='Job title (e.g., HR Manager, CEO, Developer)', max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('tracker_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('last_agent_sync_at', models.DateTimeField(blank=True, help_text='Last desktop app heartbeat', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshots_enabled', models.BooleanField(default=True, help_text='Allow screenshot capture')),
                ('website_tracking_enabled', models.BooleanField(default=True, help_text='Track visited websites')),
                ('app_tracking_enabled', models.BooleanField(default=True, help_text='Track used applications')),
                ('screenshot_interval_seconds', models.IntegerField(default=600, help_text='Time between screenshots')),
                ('idle_threshold_seconds', models.IntegerField(default=300, help_text='Time inactive before counting as idle')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Policy',
                'verbose_name_plural': 'Company Policies',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_tagline', models.CharField(blank=True, default='Employee Activity Tracker', max_length=500)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional custom map embed URL', max_length=500, null=True)),
                ('terms_url', models.URLField(blank=True, max_length=500, null=True)),
                ('privacy_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cookies_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (recommended: 200x200px)', null=True, upload_to='company/')),
                ('favicon', models.ImageField(blank=True, help_text='Website favicon (recommended: 32x32px)', null=True, upload_to='company/')),
                ('primary_color', models.CharField(default='#667eea', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Secondary brand color (hex)', max_length=7)),
                ('daily_target_hours', models.FloatField(default=8.0)),
                ('idle_threshold_minutes', models.IntegerField(default=5)),
                ('screenshot_retention_days', models.IntegerField(default=30)),
                ('employee_limit', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success_note', models.TextField(blank=True, help_text="Employee's note upon completion")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_seconds', models.IntegerField(default=0)),
                ('active_seconds', models.IntegerField(default=0)),
                ('idle_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, help_text='Full URL path including query parameters', null=True)),
                ('active_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_usages', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_usages', to='core.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/')),
                ('capture_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.CharField(blank=True, max_length=500)),
                ('active_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to='core.company')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to='core.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_type', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('duration_seconds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.company')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('COMPANY_CREATED', 'Company Created'), ('COMPANY_SUSPENDED', 'Company Suspended'), ('COMPANY_REACTIVATED', 'Company Reactivated'), ('PLAN_CHANGED', 'Plan Changed'), ('POLICY_CHANGED', 'Policy Changed'), ('EMPLOYEE_ADDED', 'Employee Added'), ('EMPLOYEE_REMOVED', 'Employee Removed'), ('EMPLOYEE_DEACTIVATED', 'Employee Deactivated'), ('EMPLOYEE_REACTIVATED', 'Employee Reactivated'), ('KEY_ROTATED', 'API Key Rotated'), ('REPORT_EXPORTED', 'Report Exported'), ('SETTINGS_CHANGED', 'Settings Changed'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.company')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', '-timestamp'], name='core_auditl_company_def1b0_idx'), models.Index(fields=['action_type', '-timestamp'], name='core_auditl_action__f8907a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_active_seconds', models.IntegerField(default=0)),
                ('total_idle_seconds', models.IntegerField(default=0)),
                ('num_employees_active', models.IntegerField(default=0)),
                ('num_sessions', models.IntegerField(default=0)),
                ('num_screenshots', models.IntegerField(default=0)),
                ('storage_used_mb', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='core.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date'], name='core_compan_company_b12cf0_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
