# Generated by Django 6.0.1 on 2026-02-01 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID (e.g., price_1ABC...)', max_length=255)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, help_text='Monthly cost in USD', max_digits=10)),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0, help_text='Annual cost in USD (if applicable)', max_digits=10)),
                ('max_employees', models.IntegerField(default=5, help_text='Max concurrent employees')),
                ('max_agents', models.IntegerField(default=5, help_text='Max active desktop agents')),
                ('max_storage_gb', models.IntegerField(default=10, help_text='Max screenshot storage in GB')),
                ('screenshot_retention_days', models.IntegerField(default=30, help_text='Days to keep screenshots')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Features JSON: {screenshots: bool, website_tracking: bool, app_tracking: bool, ...}')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='StripeBillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(help_text='Current billing period start')),
                ('current_period_end', models.DateTimeField(help_text='Current billing period end')),
                ('auto_renewal', models.BooleanField(default=True)),
                ('default_payment_method_id', models.CharField(blank=True, help_text='Stripe Payment Method ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='core.company')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptiontier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('AGENT_OFFLINE', 'Agent Offline'), ('AGENT_NEVER_SYNCED', 'Agent Never Synced'), ('PAYMENT_FAILED', 'Payment Failed'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('USAGE_HIGH', 'High Usage'), ('POLICY_CHANGED', 'Policy Changed'), ('SYSTEM_ERROR', 'System Error')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_employee_id', models.IntegerField(blank=True, help_text='Related User ID if agent-related', null=True)),
                ('related_data', models.JSONField(blank=True, default=dict, help_text='Additional context as JSON')),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='core_alertn_company_354c64_idx'), models.Index(fields=['is_read', '-created_at'], name='core_alertn_is_read_9c58eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('VOID', 'Void'), ('UNCOLLECTIBLE', 'Uncollectible')], default='OPEN', max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('issued_date', models.DateTimeField(help_text='When invoice was created')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hosted_invoice_url', models.URLField(blank=True, help_text='Stripe hosted invoice URL')),
                ('pdf_url', models.URLField(blank=True, help_text='PDF invoice URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_invoices', to='core.company')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.stripebillingsubscription')),
            ],
            options={
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['company', '-issued_date'], name='core_stripe_company_839fc7_idx'), models.Index(fields=['status', '-issued_date'], name='core_stripe_status_461ce6_idx')],
            },
        ),
    ]
