# Generated by Django 6.0.1 on 2026-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title (e.g., HR Manager, CEO, Developer)', max_length=100, null=True),
        ),
    ]
