# Generated by Django 6.0.1 on 2026-01-27 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name_plural': 'Company Settings'},
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_tagline',
            field=models.CharField(blank=True, default='Employee Activity Tracker', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website favicon (recommended: 32x32px)', null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (recommended: 200x200px)', null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color',
            field=models.CharField(default='#667eea', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_color',
            field=models.CharField(default='#764ba2', help_text='Secondary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
