# Generated by Django 6.0.1 on 2026-02-01 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptiontier_stripebillingsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL', max_length=500)),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#28a745', help_text='Hex color code', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('custom_domain', models.CharField(blank=True, help_text='e.g., tracker.yourcompany.com', max_length=255)),
                ('email_from_name', models.CharField(blank=True, max_length=100)),
                ('email_from_address', models.EmailField(blank=True, max_length=254)),
                ('email_footer_text', models.TextField(blank=True)),
                ('login_page_title', models.CharField(default='Employee Tracker Login', max_length=100)),
                ('login_page_subtitle', models.CharField(blank=True, max_length=200)),
                ('login_background_image', models.ImageField(blank=True, null=True, upload_to='branding/backgrounds/')),
                ('company_website', models.URLField(blank=True, max_length=500)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Company Brandings',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Monthly budget', max_digits=12)),
                ('cost_center_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartments', to='core.department')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_members', to='core.department'),
        ),
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SAML2', 'SAML 2.0'), ('AZURE_AD', 'Azure Active Directory'), ('GOOGLE', 'Google Workspace'), ('OKTA', 'Okta'), ('CUSTOM', 'Custom OAuth2')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enforce_sso', models.BooleanField(default=False, help_text='Require SSO for all users')),
                ('saml_entity_id', models.CharField(blank=True, max_length=500)),
                ('saml_sso_url', models.URLField(blank=True, help_text='Identity Provider SSO URL', max_length=500)),
                ('saml_slo_url', models.URLField(blank=True, help_text='Single Logout URL', max_length=500)),
                ('saml_x509_cert', models.TextField(blank=True, help_text='X.509 Certificate')),
                ('oauth_client_id', models.CharField(blank=True, max_length=255)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255)),
                ('oauth_authorization_url', models.URLField(blank=True, max_length=500)),
                ('oauth_token_url', models.URLField(blank=True, max_length=500)),
                ('oauth_user_info_url', models.URLField(blank=True, max_length=500)),
                ('role_mapping', models.JSONField(blank=True, default=dict, help_text='Map SSO roles to app roles')),
                ('auto_provision_users', models.BooleanField(default=False, help_text='Auto-create users on first login')),
                ('default_role', models.CharField(default='EMPLOYEE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='core.company')),
            ],
            options={
                'verbose_name': 'SSO Configuration',
                'verbose_name_plural': 'SSO Configurations',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_members', models.IntegerField(default=10, help_text='Maximum team size')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.department')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_level', models.CharField(choices=[('USER', 'User'), ('TEAM', 'Team'), ('DEPARTMENT', 'Department'), ('COMPANY', 'Company')], max_length=20)),
                ('date', models.DateField()),
                ('total_work_time', models.IntegerField(default=0, help_text='Total work time in minutes')),
                ('productive_time', models.IntegerField(default=0, help_text='Productive time in minutes')),
                ('idle_time', models.IntegerField(default=0, help_text='Idle time in minutes')),
                ('break_time', models.IntegerField(default=0, help_text='Break time in minutes')),
                ('total_activities', models.IntegerField(default=0)),
                ('app_switches', models.IntegerField(default=0)),
                ('website_visits', models.IntegerField(default=0)),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to='core.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to='core.team')),
            ],
            options={
                'ordering': ['-date', 'company'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('PRODUCTIVITY', 'Productivity Report'), ('TIME_UTILIZATION', 'Time Utilization'), ('DEPARTMENT_COMPARISON', 'Department Comparison'), ('ACTIVITY_HEATMAP', 'Activity Heatmap'), ('CUSTOM', 'Custom Report')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('JSON', 'JSON')], default='PDF', max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('MANUAL', 'Manual Only')], default='MANUAL', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'is_active'], name='core_depart_company_0d8e53_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='core_depart_parent__aa9311_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['company', 'is_active'], name='core_team_company_bc7d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department'], name='core_team_departm_85bd6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['company', 'date'], name='core_produc_company_912d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['metric_level', 'date'], name='core_produc_metric__57f754_idx'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['user', 'date'], name='core_produc_user_id_ca21c0_idx'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['team', 'date'], name='core_produc_team_id_db8a01_idx'),
        ),
        migrations.AddIndex(
            model_name='productivitymetric',
            index=models.Index(fields=['department', 'date'], name='core_produc_departm_99120b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productivitymetric',
            unique_together={('company', 'metric_level', 'date', 'user', 'team', 'department')},
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['company', '-created_at'], name='core_analyt_company_e4ee77_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type', 'is_active'], name='core_analyt_report__c4e860_idx'),
        ),
    ]
