# Generated by Django 6.0.1 on 2026-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='cookies_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional custom map embed URL', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='privacy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='terms_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
