# Generated by Django 6.0.1 on 2026-01-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteusage',
            name='url',
            field=models.TextField(blank=True, help_text='Full URL path including query parameters', null=True),
        ),
    ]
