# Generated by Django 6.0.1 on 2026-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_websiteusage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_tagline',
            field=models.CharField(blank=True, default='Employee Activity Tracker', max_length=500),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='cookies_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional custom map embed URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='privacy_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='terms_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
