# Generated by Django 6.0.1 on 2026-02-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='config_sync_interval_seconds',
            field=models.IntegerField(default=10, help_text='How often desktop app checks for config updates (5-60 seconds)'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='config_version',
            field=models.IntegerField(default=1, help_text='Incremented on each change'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='enable_idle_detection',
            field=models.BooleanField(default=True, help_text='Detect idle time'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='enable_keyboard_tracking',
            field=models.BooleanField(default=False, help_text='Track keyboard activity'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='enable_mouse_tracking',
            field=models.BooleanField(default=False, help_text='Track mouse activity'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='local_data_retention_days',
            field=models.IntegerField(default=30, help_text='Keep local database records for N days'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='max_screenshot_size_mb',
            field=models.IntegerField(default=5, help_text='Maximum screenshot file size in MB (1-50)'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='notification_interval_minutes',
            field=models.IntegerField(default=30, help_text='Notification reminder interval in minutes (0 = disabled)'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='screenshot_quality',
            field=models.IntegerField(default=85, help_text='Screenshot JPEG quality (50-95)'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='show_tracker_notification',
            field=models.BooleanField(default=True, help_text='Show system tray notifications'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='idle_threshold_seconds',
            field=models.IntegerField(default=300, help_text='Time inactive before counting as idle (60-1800 seconds)'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='screenshot_interval_seconds',
            field=models.IntegerField(default=600, help_text='Time between screenshots (30-3600 seconds)'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
